port: 3000
app_id: "your_app_id_here"
dashscope_id: "your_dashscope_id_here"

# 新增 MySQL 数据库配置
db:
  host: "localhost"
  port: 3306
  user: "your_username"
  password: "your_password"
  database: "your_database_name"